import { BiAbacus, BiCategory } from "react-icons/bi";
import {
  BsCart2,
  BsClockHistory,
  BsEye,
  BsEyeSlash,
  BsFillXCircleFill,
  BsQuestionSquare,
  BsShieldCheck,
  BsShieldExclamation,
  BsSignpost,
  BsSortDown,
} from "react-icons/bs";
import { FiEdit, FiLogIn, FiLogOut, FiMinus, FiPlus } from "react-icons/fi";
import { HiOutlineUser, HiOutlineUsers } from "react-icons/hi";
import { IoImagesOutline, IoSearch } from "react-icons/io5";
import { TfiLayoutSlider } from "react-icons/tfi";
import { VscLocation, VscThreeBars } from "react-icons/vsc";

import {
  RiArrowDropDownLine,
  RiArrowDropLeftLine,
  RiArrowDropRightLine,
  RiArrowDropUpLine,
  RiArrowRightLine,
  RiChat1Line,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiDeleteBinLine,
  RiHandbagLine,
  RiHeartLine,
  RiHome6Line,
  RiInstagramFill,
  RiLinkedinFill,
  RiMore2Fill,
  RiPencilRuler2Line,
  RiPhoneFill,
  RiSave2Line,
  RiStarFill,
  RiTimeFill,
  RiTwitterFill,
  RiUserLocationFill,
  RiUserLocationLine,
  RiWallet3Line,
  RiYoutubeFill,
} from "react-icons/ri";

import { CgSandClock } from "react-icons/cg";

const Icons = {
  Twitter: RiTwitterFill,
  Linkedin: RiLinkedinFill,
  Instagram: RiInstagramFill,
  Youtube: RiYoutubeFill,
  Cross: BsFillXCircleFill,
  Times: RiTimeFill,
  Wallet: RiWallet3Line,
  Rule: RiPencilRuler2Line,
  More: RiMore2Fill,
  ShieldCheck: BsShieldCheck,
  Check: RiCheckboxCircleLine,
  Filter: BiAbacus,
  Save: RiSave2Line,
  Star: RiStarFill,
  Sort: BsSortDown,
  Eye: BsEye,
  EyeSlash: BsEyeSlash,
  Cart: BsCart2,
  Login: FiLogIn,
  Logout: FiLogOut,
  Exclamation: BsShieldExclamation,
  Bars: VscThreeBars,
  User: HiOutlineUser,
  Users: HiOutlineUsers,
  Category: BiCategory,
  Question: BsQuestionSquare,
  Search: IoSearch,
  ArrowLeft: RiArrowDropLeftLine,
  ArrowDown: RiArrowDropDownLine,
  ArrowUp: RiArrowDropUpLine,
  ArrowRight: RiArrowRightLine,
  ArrowRight2: RiArrowDropRightLine,
  Edit: FiEdit,
  Clock: BsClockHistory,
  Clock2: CgSandClock,
  Heart: RiHeartLine,
  Bag: RiHandbagLine,
  Comment: RiChat1Line,
  Location: RiUserLocationLine,
  Location2: VscLocation,
  Home: RiHome6Line,
  Plus: FiPlus,
  Minus: FiMinus,
  Close: RiCloseLine,
  UserLocation: RiUserLocationFill,
  Post: BsSignpost,
  Phone: RiPhoneFill,
  Delete: RiDeleteBinLine,
  Slider: TfiLayoutSlider,
  Image: IoImagesOutline,
};

export default Icons;
